stages:
  - healthcheck
  - contract
  - acceptance
  - functional

"Health Check":
  stage: healthcheck
  script:
    - mvn clean test -Dtest=HealthCheckTest

Contrato:
  stage: contract
  script:
    - mvn clean test -Dtest=ContractTest

Aceitação:
  stage: acceptance
  script:
    - mvn clean test -Dtest=AcceptanceTest

Funcional:
  stage: functional
  script:
    - mvn clean test -Dtest=FunctionalTest